# Generated by Django 2.1.5 on 2019-01-30 12:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Split',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='payment',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='drawee',
        ),
        migrations.RemoveField(
            model_name='room',
            name='biggest_pledger',
        ),
        migrations.RemoveField(
            model_name='room',
            name='matrix',
        ),
        migrations.RemoveField(
            model_name='room',
            name='total_balance',
        ),
        migrations.RemoveField(
            model_name='user',
            name='balance',
        ),
        migrations.AlterField(
            model_name='payment',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='split',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.Payment'),
        ),
        migrations.AddField(
            model_name='split',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Drawee', to=settings.AUTH_USER_MODEL),
        ),
    ]
